### ISSUE TITLE
Cannot read properties of undefined when deleting child and then parent

### ISSUE THREAD

**Issue by Ciccio99** [valtiojs/valtio-yjs#41]
This issue affects valtio-yjs specifically, as it functions correctly with vanilla valtio.

Here is a simplified example of the issue: [codesandbox](https://codesandbox.io/p/sandbox/charming-leakey-3s4ll6?file=%2Fsrc%2Findex.ts%3A60%2C26&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clplm1p7100063b6jjbftjx3h%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clplm1p7100023b6j4lphkiy6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clplm1p7100033b6jl7pafatu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clplm1p7100053b6jtlbbjbqi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clplm1p7100023b6j4lphkiy6%2522%253A%257B%2522id%2522%253A%2522clplm1p7100023b6j4lphkiy6%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clplm1p7100053b6jtlbbjbqi%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clplm1p7100043b6j0ni213v6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clplm1p7100053b6jtlbbjbqi%2522%252C%2522activeTabId%2522%253A%2522clplm1p7100043b6j0ni213v6%2522%257D%252C%2522clplm1p7100033b6jl7pafatu%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clplm1p7100033b6jl7pafatu%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 

I have an object structure similar to this:
```

type child = {
  id: string;
  parent: string;
};

type parent = {
  children: {
    [id: string]: child;
  };
};

type State = {
  parents: {
    [id: string]: parent;
  };
};
```
If I delete a child of a parent and then immediately delete the parent, then valtio-yjs throws an undefined error.

The use case for this logic is used when I'm deleting a child from a parent, and if the child is the last child in parent, then delete the parent.

This isn't a major issue, since you can get around this issue by checking if it's the last child and then just deleting the parent directly. However, seeing as this is functional with vanilla valtio, It should probably work with valtio-yjs as well.

**Comment by dai-shi** [comment]
Published https://www.npmjs.com/package/valtio-yjs/v/0.5.1, thanks to @raineorshine !
