### ISSUE TITLE
None of the demos work

### ISSUE THREAD

**Issue by corysimmons** [valtiojs/valtio-yjs#47]
![image](https://github.com/valtiojs/valtio-yjs/assets/224636/963a0a53-f72a-4a25-91de-378a71f7b906)

**Comment by dai-shi** [comment]
Hmm, maybe yjs server has changed something?

**Comment by waynebloss** [comment]
It's working, but you have to open both clients in a separate tab. The client that is embedded in the Sandbox won't work because it's not a real browser tab.

![image](https://github.com/valtiojs/valtio-yjs/assets/623736/bd27a673-b1b0-429e-b070-150beff239b3)

**Comment by waynebloss** [comment]
For what it's worth - I do still get the errors shown in the devtools, but I'm just learning how to use yjs so I can't help you there.

**Comment by corysimmons** [comment]
Oh strange. I definitely opened one tab to `https://ox3iy.csb.app/` in a normal window and another in a private window, and it didn't work, but maybe it was an extension somehow interfering because when I opened both in private windows it worked. 😬 My bad! Sorry for the alarm and thanks @waynebloss

**Comment by raineorshine** [comment]
It's likely that the websocket server is not working at all, and what you're seeing is cross-tab communication (which is provided out-of-the-box by y-websocket).

It could be a CORS setting or something else with the server that changed. It's worth noting that the [YJS ProseMirror demo](https://demos.yjs.dev/prosemirror/prosemirror.html) is connecting to the server and working between normal and private tabs. But for demo purposes, the cross-tab functionality is arguably sufficient.

**Comment by corysimmons** [comment]
>what you're seeing is cross-tab communication (which is provided out-of-the-box by y-websocket)

Oh, interesting. Either way, the CodeSandbox demo doesn't seem to work very well out of the box so maybe I'll reopen this unless the author decides it isn't important (in which case feel free to close, I have my implementation of valtio-yjs working great on my project already 😄).

**Comment by dai-shi** [comment]
Can anyone fork the codesandbox links and fix it?

**Comment by corysimmons** [comment]
@dai-shi Do you mind if I use y-sweet instead of y-websocket for the reason @raineorshine mentioned above?

Users would need to login to https://app.y-sweet.cloud/ to get a connection string and test the demos like `CONNECTION_STRING=yss://foo.bar@y-sweet.net/p/baz/ npm run dev`, or we could use a shared public one if we added a bad word filter.

Let me know what you think and I'll make a little demo.

**Comment by dai-shi** [comment]
So, doesn't it work with codesandbox?

Anyway, having new demos is fine. Please feel free to try.

**Comment by MH4GF** [comment]
Using https://github.com/yjs/y-webrtc worked on codesandbox 👍🏻 

https://github.com/valtiojs/valtio-yjs/assets/31152321/59932066-7ac9-4db3-b039-0c0943e140e8

https://codesandbox.io/p/devbox/valtio-yjs-demo-8vyktr?file=%2Fsrc%2FApp.jsx%3A9%2C7
